dlang-community/DCD

- src/modulecache.d
19c8468 seemed to have caused a bug because tokens & parseStringCache have shared lifetimes.
Minimum reproducible example:
import std.algorithm;
void main(string[] args)
{
std.algorithm.BoyerMooreFinder(
}
test:
./bin/dcd-client -c 85 main.d
no output
./bin/dcd-client -c 83 main.d
crash
With fix:
./bin/dcd-client -c 85 main.d
calltips
this(Range needle)
./bin/dcd-client -c 83 main.d
BoyerMooreFinder	s
boyerMooreFinder	f
> Reference to StringCache outliving scope

- src/server.d
1) look for /etc/dcd.conf if $HOME is defined but there is no dcd.conf there
2) include missing filename in path
> Fixup for /etc/dcd.conf support

- src/actypes.d
The classinfo property was mispelled as classInfo in actypes.d, resulting in
incorrect completions.
See: http://dlang.org/property.html#classinfo
> Fix spelling of classinfo.

- src/client/client.d
- src/common/socket.d
Checking the repo out and running dub to build on windows would
give two compiler errors, one because UnixAddress is not defined
another because a function misses a return statement if Unix sockets
are not possible.
> Fix compiler errors on windows

- README.md
- src/server/server.d
- use a replaceAll of a compile time regex to expand environment variables of
the form ${ENV_VAR} in the import paths
- added a unit test for the regex
> Added environment variable expansion support to the server config file

- src/server/autocomplete.d
- tests/tc031/expected1.txt
- tests/tc031/file.d
- tests/tc031/run.sh
- It was the cast to string that corrupted something. With `.idup` on the appender it works again.
- I've also took the initiative to use functions instead of the Escaper struct.
- Regression test included.
> fix #313 - ddoc, overloads sets broken

- src/server/autocomplete.d
- tests/tc032/expected1.txt
- tests/tc032/file.d
- tests/tc032/run.sh
https://github.com/Hackerpilot/DCD/issues/308
Seems to work and breaks no tests, but I'm not sure if this is the right way to fix it.
> autocomplete: Fix goto-declaration for import statements

- makefile
(triviality noticed when updating DCD package)
DCD now uses all-at-once build mode and this variable is not
actually used anywhere.
> Remove unused OBJDIR from makefile

- src/common/dcd_version.d
I guess this should have been in alpha4 itself, but this is better than nothing?
> bump version num to v0.9.0-alpha4

- src/server/autocomplete.d
- tests/tc051/expected.txt
- tests/tc051/file.d
- tests/tc051/run.sh
It appears that the problem was that an identifier which is part of an UDA was seen as part of an expression. Unfortunately It seems that the fix also introduces a small regression: No call tips anymore on the UDA constructor, e.g (`struct UDA{int i;} @UDA(`). Minor issue IMO.
> fix #369, No completion after UDA

- src/server/autocomplete.d
- tests/tc052/file.d
- tests/tc052/run.sh
Note well that this is only a workaround and that there must be a deeper and nasty bug elsewhere. If someone has the time to cook a better fix see test case 52. For a reason the request leads to a crash if ddoc is requested for a string literal that ends with a multi byte character.
> prevent a range error, close #368

- src/server/autocomplete.d
- tests/tc051/expected1.txt
- tests/tc051/file1.d
- tests/tc051/run.sh
In the PR #369 I mentioned that call tip request for an UDA will be broken. Unfortunately today i've discovered that it breaks also all the other features (ddoc, goto def are useful for an UDA). This PR rewrites the fix so that it's only applied to the autocompletion.
> fixup #369, completion after UDA, not only calltips broken

- src/server/autocomplete.d
- tests/tc051/expected2.txt
- tests/tc051/file2.d
- tests/tc051/run.sh
Sorry, again another feature broken. Dot completion didn't work anymore if an UDA was found in the tokens and this even if the UDA was for another, very distant, declaration.
> fixup #369, dot completion broken in bodies + handle templatized UDAs

- .travis.sh
- .travis.yml
- dub.json
- tests/run_tests.sh
The dub has two test failures which I'll look into, and the OSX version gets `std.socket.SocketOSException@std/socket.d(2778): Unable to connect socket: No such file or directory` sometimes for the tests. Seems to be hit or miss. Don't have a mac so can't test it, might end up just removing osx from travis.
> Refactor travis config to include dub build and ldc.

- src/common/constants.d
There's no emergency, needed after next dmd release.
> support for the getLinkage trait

- src/common/constants.d
[Upstream dmd feature](https://github.com/dlang/dmd/commit/355a1ccadea83488f4879d946b53ef11874dba9b). Like yesterday, no emergency.
> add support for the getFunctionVariadicStyle trait

- dub.json
- src/server/autocomplete.d
I've verified locally, i don't see how to check this easily online. Also Cybershadow can't test anymore with the project that led to the report.
So to check:
- choose a repo with packages (sub folder containing sources).
- in sudo forbid access to one of the package.
- start dcd / add the repo to the import
- try to get import completion (`import.stuff.`) for the package that matches to the folder previously chmod-ed
after the fix no crash.
> fix #319 - server crash when an import path contains a folder that's not accessible

- src/server/main.d
`listen(0)` in general means that you can't connect to the server at all. That it still works is at least in parts due to SYN cookies being enabled in most Linux systems. These allow connections even if an attacker spams the server with unacknowledged connection requests thereby filling up the backlog. Being behind a firewall/router I have this disabled in the kernel and witness the 'proper' socket behavior: The client waits for the server to make room in its size 0 backlog until the TCP timeout happens.
Both enabling SYN cookies and raising the backlog to at least 1 makes it work. Since DCD works purely on the loopback network which seems to accept connections synchronous on Linux at least, a value of 1 is probably all that's technically required, but some larger number (32) wont do any …
> Provide backlog for socket.listen()

- dub.json
- tests/tc057/expected.txt
- tests/tc057/file.d
- tests/tc057/run.sh
This is till related to the dparse bug that fixes parsing of AA & static array literals. The consequence in DCD was completion broken, just like in the test.
> fix, completion broken after AA lit

- .gitmodules
- README.md
- man1/dcd-client.1
- man1/dcd-server.1
I noticed that in some places the url was still github.com/Hackerpilot/DCD, I updated it to be dlang-community/DCD.
> Updated old URLs - Changed Hackerpilot/DCD to dlang-community/DCD

- src/server/autocomplete/complete.d
- src/server/autocomplete/util.d
- tests/tc058/expected1.txt
- tests/tc058/file.d
- tests/tc058/run.sh
This PR combines all the duplicate skip implementations in the util.d file + using big case mixin enums where possible
This also fixes a previously unknown bug (or more likely never reported) in the calltips where it was often off in more complex function calls as seen in the created test case
> Fix calltips often reporting wrong functions

- src/server/server.d
The config file location was moved a long time ago so it's not really needed anymore
> Remove warning about old config location

- dub.json
Related to https://github.com/dlang-community/libdparse/issues/176
> update libdparse to prevent case of OutOfMem

- src/dcd/server/main.d
This quiets some deprecation warnings.
> Update StopWatch use and containers submodule for 2.078.0

- README.md
Used to be okay i the past but GH doesn't render them anymore when the sharp is contiguous to the text
> [TRIVIAL] Fix a H1 title in the README

- dub.json
checked for back compat back to2.076.1, which is the version i still use for prebuild Coedit DCD because of another bug.
> fix #445 - Cannot build via dub on windows

- .travis.sh
- dub.json
To get dub build in line with make and build.bat, binary output should end up in bin/.
> Moving dub binaries to bin/

- .travis.yml
Apparentely casing is important as it failed with:
> Skipping a deployment with the releases provider because this repo's name does not match one specified in .travis.yml's deploy.on.repo: dlang-community/dcd
https://travis-ci.org/dlang-community/DCD/jobs/371909754
> [trivial] Fix Travis deployment

- tests/run_tests.sh
Should prevent the failures seen in https://github.com/dlang-community/DCD/issues/455 and allow to re-enable DCD at the project tester.
https://github.com/dlang/ci/pull/204
> Make the test_runner more stable on the Project Tester - fix #455

- .travis.yml
- appveyor.yml
- dmd-nightly is already done by the D project tester.
- dmd-beta is most of the time useless because the beta is older than the latest dmd
> Remove dmd-beta and dmd-nightly from TravisCI

- release-windows.sh
See also: https://github.com/dlang-community/DCD/issues/472
Apparentely deploying with 2.076.0 doesn't work.
> Upgrade to win80 to build DScanner

- dub.json
While updating D-Scanner for phobos a possible range violation in dsymbol has been discovered.
Also a custom function body parser was not yet adapted to support the expressions-based contracts.
Dparse is also updated to allow the new syntax of enum members, which will come with DMDFE 2.082
> Update dsymbol and dparse

- dub.json
Because of auto-decoding the file contained a  dstring.
> fix #528 - Bad dub hash generation

- src/dcd/common/messages.d
It's been more than a full year now that the advanced output mode is there.
> remove deprecated funcs in messages.d

- src/dcd/server/autocomplete/complete.d
- tests/tc_currmod_fqn/file3.d
- tests/tc_currmod_fqn/run.sh
It was due to the `isSame` default value, never invalidated when the loop didn't start at all.
> fix issue 557 - Module name completion should not complete anything

- dub.json
- src/dcd/server/autocomplete/doc.d
- tests/tc_ditto_scopes/expected1.txt
- tests/tc_ditto_scopes/expected3.txt
- tests/tc_ditto_scopes/expected4.txt
- tests/tc_ditto_scopes/expected5.txt
- tests/tc_ditto_scopes/expected6.txt
- tests/tc_ditto_scopes/expected7.txt
- tests/tc_ditto_scopes/expected8.1.txt
- tests/tc_ditto_scopes/expected8.2.txt
- tests/tc_ditto_scopes/expected8.3.txt
- tests/tc_ditto_scopes/expected8.txt
- tests/tc_ditto_scopes/expected9.txt
- tests/tc_ditto_scopes/file.d
- tests/tc_ditto_scopes/run.sh
- tests/tc_extended_ditto/expected1.txt
- tests/tc_extended_ditto/file.d
- tests/tc_extended_ditto/run.sh
adds a unittest for `/// ditto` in extended mode
Depends on dlang-community/dsymbol#111
I should probably add a few scope unittests for ditto first
> Extended mode ditto comment support

- tests/tc036/run.sh
- tests/tc_issue558/expected.txt
tc036 added an import file but didn't remove it again. Another unittest just added it to the expected results list, though it should get removed after running the unittest
But there seems to be an issue with import files bleeding their scope into other stuff.
> Fix file import test bleeding into other tests

- dub.json
- tests/tc_if_auto_array/expected.txt
- tests/tc_if_auto_array/file.d
- tests/tc_if_auto_array/run.sh
I suspect that the bug in dsymbol affected other more realistic cases than the one that had allowed to detect the problem so finally i decided to propagate the fix in dcd without waiting the next big change.
> fix wrong completion for if variable initialized with an array

- src/dcd/server/autocomplete/util.d
This has happened once with some complete incorrect code, unfortunately hard to reproduce but easy to prevent.
> fix #561 - possible range violation

- src/dcd/client/client.d
On windows the exceptions caused by socket connections are not catched and therefore causes windows dialogs like this one
This makes the usage of DCD within IntelliJ almost unusuable as it hangs (due to the dialogs which will only be shown after closing IntelliJ).
This pull request wraps the client main logic within a separate function and catches all exceptions.
> Fix client exception handling

- dub.json
stuff like
```d
/** line1
line2
* listitem1
* listitem2
* listitem3 */
```
Were not undecorated correctly. Not only that, there would be more examples.
> update dparse to fix bad looking ddoc hints in some cases

- common/src/dcd/common/messages.d
- src/dcd/server/main.d
- tests/tc_empty_requests/run.sh
this is a or-combined mask of the request kinds which operate on `request.sourceCode`. Before if a client sent a request without source code (with empty source) to one of these commands, the server would
crash with an assertion failure, now the server returns an empty response.
> add RequestKind.requiresSourceCode, fix #617

- .gitmodules
- .travis.sh
- .travis.yml
- dub.json
- makefile
I would make this the last commit for DCD v0.13.0 and release (because last release is over a year old, the binary had linking issues on OSX and completion was broken because protection scopes were broken and private was no longer shown, which is fixed since dsymbol 0.11.0)
Because this release fixes the private protection issue through new dsymbol (since 0.11.0) we also need to bump libdparse to at least 0.15.0 so no older libdparse versions are supported. However I added the d-test-utils test_with_package script to support multiple libdparse versions in the future like in the other projects.
I would suggest after this we should create a milestone for v0.14.0 again and maybe refer to the milestones in a contributors file or something?
> use d-test-utils & bump libdparse to 0.15.x

- src/dcd/server/main.d
Not sure why this was missing.
> Add the ignoreConfig option to the --help output of dcd-server.

- .travis.yml
- setup-ldc-windows.sh
The LDC used for release hasn't been updated in years,
and was severely lacking behind.
The script used is very clearly a copy of the one in DUB,
which has been overhauled in dlang/dub#1849,
so copying those improvements over.
> Update release LDC to v1.23.0

- .github/workflows/ci.yml
dub builds into `bin` folder, so take the files from there. Adjust working-directory so we don't accidentally create a folder named "bin" inside the archives.
> make CI artifacts inside bin folder

- src/dcd/server/autocomplete/localuse.d
- tests/tc033/run.sh
makes behavior consistent with find declaration - where the first character of a token does not yield results, but the last does
Before there was a weird edge case of it just finding the declaration on first character and no uses and finding nothing on the last character.
> fix --localUse off-by-one error

- src/dcd/server/autocomplete/ufcs.d
- tests/tc_ufcs_calltip_in_func/file.d
- tests/tc_ufcs_calltip_in_func/run.sh
For consistency and to allow future changes to type matching (e.g. implicit type conversion)
> use `isCallableWithArg` in paren completion

- src/dcd/client/client.d
- src/dcd/server/main.d
should fix DMD 2.101+ compatibility, where std.experimental.logger was moved into std.logger
I don't think there is any other way to do it right now than to cast away the shared.
> fixed shared logger usage

- .github/workflows/ci.yml
- .github/workflows/release.yml
`actions/checkout@v2` uses Node 12 which had end of life in April, and it may be removed in Summer 2023 ([GitHub Blog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)). This PR addresses this with the version increase. It should not break anything.
> Updated the CI checkout action version to v3

- dsymbol/dub.json
- dub.json
Mainly adds some new syntax parsing support, fixes syntax errors with scope in foreach and others.
Deprecations can be fixed later once we drop libdparse 0.20.0 support
> bump libdparse to 0.21.1

- .github/workflows/ci.yml
- .gitignore
- common/dub.sdl
- dub.selections.json
Fixes msgpack-d deprecations, allows minor bumps upstream, allows DUB dependees to use other msgpack-d versions.
> upgrade msgpack to ~>1.0

- .github/workflows/ci.yml
- .github/workflows/release.yml
Build on Ubuntu 20.04 instead of 22.04 for more linux compatibility with pre-built binaries.
> downgrade ubuntu version for ABI compatibility

- dsymbol/src/dsymbol/conversion/package.d
- dsymbol/src/dsymbol/conversion/third.d
To make things a little bit cleaner
I have more stuff planned for a different PR for template/auto stuff, so that's gonna be a good place for it to avoid clutter
Also the license stuff above modules needs to be updated (year + contributors)
> Move third phase to its own module

- dsymbol/dub.json
- dub.json
- dub.selections.json
for dsymbol I lifted the strict max-version restrictions, as other projects like dscanner depend on it and often don't break. (backwards compatibility with libdparse should stay in for a while anyway)
> upgrade to libdparse 0.22.0

- dsymbol/src/dsymbol/ufcs.d
- src/dcd/server/autocomplete/complete.d
- src/dcd/server/autocomplete/util.d
moving UFCS logic into dsymbol, since it makes sense architecturally.
> moving ufcs logic to dsymbol

- README.md
- common/src/dcd/common/messages.d
- dsymbol/src/dsymbol/builtin/symbols.d
- dsymbol/src/dsymbol/conversion/first.d
- dsymbol/src/dsymbol/conversion/second.d
- dsymbol/src/dsymbol/symbol.d
- dsymbol/src/dsymbol/tests.d
- src/dcd/client/client.d
- src/dcd/server/autocomplete/complete.d
- src/dcd/server/autocomplete/util.d
- tests/tc059/expected1.txt
- tests/tc059/file.d
- tests/tc061/expected1.txt
- tests/tc_extended_ditto/expected1.txt
- tests/tc_extended_types/expected1.txt
- tests/tc_extended_types/file.d
- tests/tc_extended_types/run.sh
- tests/tc_import_symbol_list/run.sh
- tests/tc_pointer_type_printing/expected1.txt
- tests/tc_pointer_type_printing/file.d
- tests/tc_pointer_type_printing/run.sh
- tests/tc_pointers/expected1.txt
- tests/tc_pointers/file.d
- tests/tc_pointers/run.sh
- tests/tc_recursive_public_import/run.sh
supersedes PR fix #715 
@ryuukk this supersedes that PR you made that extended the type details to `foo -> T` syntax. I decided to only have the resolved type here, there is a fallback to use the function name on unknown types though. We could probably expose this information elsewhere though and show it somehow in serve-d.
@vushu there is a single UFCS line fix in here, which you probably want to include in your PR as well
If any of you could also review, that would be nice.
> Properly implement pointer types & resolve pointers, arrays and AAs in output

- dsymbol/src/dsymbol/tests.d
- dsymbol/src/dsymbol/ufcs.d
- tests/tc_ufcs_array_type_completion/expected_array_test.txt
- tests/tc_ufcs_array_type_completion/file.d
- tests/tc_ufcs_array_type_completion/run.sh
- tests/tc_ufcs_pointer_type_completion/expected_pointer_test.txt
- tests/tc_ufcs_pointer_type_completion/file.d
- tests/tc_ufcs_pointer_type_completion/run.sh
- tests/tc_ufcs_struct_completion/fooutils/fooutils.d
I discovered that UFCS completion didn't work correctly with pointer type, this PR should resolve it.
> Adding ufcs to match with type of pointer

- dsymbol/src/dsymbol/ufcs.d
- tests/tc_ufcs_alias_this_completion/alias_this_on_function.d
- tests/tc_ufcs_alias_this_completion/expected_alias_this_on_function_test.txt
- tests/tc_ufcs_alias_this_completion/expected_plenty_alias_this_defined_test.txt
- tests/tc_ufcs_alias_this_completion/expected_plenty_alias_this_defined_test2.txt
- tests/tc_ufcs_alias_this_completion/plenty_alias_this_defined.d
- tests/tc_ufcs_alias_this_completion/run.sh
I have refactored the  type matching algorithm for UFCS, to make it more reusable and making it non recursive.
> refactoring match algorithm to not use recursion for UFCS

- dsymbol/src/dsymbol/builtin/symbols.d
- dsymbol/src/dsymbol/conversion/first.d
- dsymbol/src/dsymbol/conversion/second.d
- dsymbol/src/dsymbol/symbol.d
- src/dcd/server/autocomplete/complete.d
- src/dcd/server/autocomplete/util.d
- tests/tc_template_bang_completion/expected.txt
- tests/tc_template_bang_completion/expected2.txt
- tests/tc_template_bang_completion/expected3.txt
- tests/tc_template_bang_completion/expected4.txt
- tests/tc_template_bang_completion/expected5.txt
- tests/tc_template_bang_completion/expected6.txt
- tests/tc_template_bang_completion/file.d
- tests/tc_template_bang_completion/run.sh
I am attempting to add bang completion for templated symbols, for now it should show calltip for functions, structs and classes.
I sadly couldn't figure out to get it working with serve-d.
> adding bang completion for template func, struct, class

- dsymbol/dub.json
- dsymbol/src/dsymbol/conversion/first.d
- dsymbol/src/dsymbol/tests.d
- dub.json
- dub.selections.json
supersedes #737 
will properly update libdparse versions once release version is out
> Update to next libdparse version

- dsymbol/src/dsymbol/conversion/package.d
- dsymbol/src/dsymbol/conversion/second.d
- dsymbol/src/dsymbol/conversion/third.d
- dsymbol/src/dsymbol/tests.d
- tests/tc717/expected.txt
- tests/tc717/file.d
- tests/tc717/run.sh
Run a lightweight version of secondPass to make sure no symbols are left out
Fixes issue #717 
(This 1st commit only contains the test, to trigger the error, then i'll commit the actual fix)
> Ensure no symbols are left out

- dsymbol/src/dsymbol/symbol.d
I just got a dcd-server crash about it, the type was null
> Ensure type is not null for symbols not yet fully resolved

- src/dcd/server/autocomplete/complete.d
`goBackToOpenParen` can return `size_t.max`, which the calling code in `getCalltipHint` did not handle (and accidentally returns via an `out` parameter).
Check for this case so we don't get an array slice error.
Before this patch I would get a crash after typing the comma in code like this:
```d
enum Foo {
X,
}
```
```
src/dcd/server/autocomplete/complete.d:366 pure nothrow @nogc @safe dcd.server.autocomplete.complete.CalltipHint dcd.server.autocomplete.complete.getCalltipHint!(std.range.SortedRange!(const(std.experimental.lexer.TokenStructure!(ubyte, "import dparse.lexer:TokenTriviaFields,TriviaToken; mixin TokenTriviaFields;").TokenStructure)[], "a < b", 0).SortedRange).getCalltipHint(std.range.SortedRange!(const(std.experimental.lexer.TokenStructure!(ubyte, "import …
```
> Fix ArraySliceError in complete.d when there is no paren.

- makefile
- tests/extra/tc_ufcs_all_kinds/run.sh
- tests/run_tests.sh
Changed the places using `/bin/bash` to `/usr/bin/env bash`. This is important for OS'es which do not have bash located here such as NixOS.
> fix(env): change the environment to be /usr/bin/env bash

- src/dcd/client/client.d
- src/dcd/server/autocomplete/doc.d
This allows to get the symbol definition, reducing the need of a extra request/computation when passing: ``--extended | -x``
> Add support for extended output when requesting symbol's documentation

- dsymbol/src/dsymbol/conversion/first.d
- dsymbol/src/dsymbol/symbol.d
As per the comment, it is no longer needed
Before:
After:
> Save memory by removing argNames from DSymbol

- common/src/dcd/common/socket.d
- makefile
- src/dcd/server/server.d
Added extra version statements for OpenBSD, NetBSD and DragonflyBSD, as these are not included in the BSD version identifier.
Also removed the line `SHELL:=/usr/bin/env bash` from the top of the makefile because most BSDs don't include bash in the base system, and the build doesn't need it anyway.
On OpenBSD, using -inline with dmd causes the compiler to crash because of insufficient memory (with 8 GB), so I added a couple of ifneq's to use -inline only if the build is not running on OpenBSD (or we could just remove -inline entirely...)
> Fix build on OpenBSD, NetBSD and DragonflyBSD

- src/dcd/server/autocomplete/util.d
should first check if the range `beforeTokens` is empty.
```
core.exception.AssertError@/usr/include/dmd/phobos/std/range/primitives.d(2504): Attempting to fetch the front of an empty array of TokenStructure!(ubyte, "import dparse.lexer:TokenTriviaFields,TriviaToken; mixin TokenTriviaFields;")
----------------
??:? _d_assert_msg [0x9293bc]
/usr/include/dmd/phobos/std/range/primitives.d:2504 pure nothrow ref @property @nogc @safe inout(std.experimental.lexer.TokenStructure!(ubyte, "import dparse.lexer:TokenTriviaFields,TriviaToken; mixin TokenTriviaFields;").TokenStructure) std.range.primitives.front!(std.experimental.lexer.TokenStructure!(ubyte, "import dparse.lexer:TokenTriviaFields,TriviaToken; mixin TokenTriviaFields;").TokenStructure).front(return scope …
```
> fix getSymbolsForCompletion raise exception
