- makefile
http://forum.dlang.org/thread/yrgfkwfcoatdwhkwmzso@forum.dlang.org#post-yrgfkwfcoatdwhkwmzso:40forum.dlang.org
as per request
> parallelize LDC build

- README.md
and this would be nice for people to know when the read the README.md
> dcd is now in homebrew

- src/autocomplete.d
Off by one error + plain stupidity.
> Fix autocomplete bug introduced by c5c342d

- build.bat
- should be easyer to maintain with variables
- output like linux in bin subfolder
> rewrite windows bat for 0.7

- src/common/constants.d
http://forum.dlang.org/post/hmrjgemnaaswuorxppon@forum.dlang.org
> added isTemplate to traits list

- src/common/messages.d
this prevented compilation under windows
> fix, win version broken, unix domain socket code defined in a runtime branch

- README.md
- src/server/autocomplete.d
- tests/tc024/expected8.txt
- tests/tc024/file.d
- tests/tc024/run.sh
https://github.com/Hackerpilot/DCD/issues/311
> Fix issue #311 (Ambiguous newlines in --doc output)

- tests/tc016/expected2.txt
In addition to the latest additions on dsymbol such as completing `aa.clear()`, this will make PR #328 work
> Updated dsymbol submodule & updated tests accordingly

- dub.json
> tab -> space

- src/common/constants.d
Yet another one ! 
See dmd [PR](https://github.com/dlang/dmd/pull/6829).
> add support for the getParameterStorageClasses trait

- src/common/dcd_version.d
I didn't know we have to do that when a git tag is added.
> [TRIVIAL] update version for --version

- src/common/dcd_version.d
I'll handle the release in the next 2 hours (merge + announce on the  NG). Still time to review the changelog draft or for you @Hackerpilot handle this.
> update version for 0.9.0 stable

- dub.json
- tests/tc056/expected.txt
- tests/tc056/file.d
- tests/tc056/run.sh
This was certainly not the worst case of auto-completion failure. I even doubt that anyone has ever encountered it.
> fix #400 - handle completion for auto bools

- dub.json
- tests/tc007/expected1.txt
- tests/tc016/expected1.txt
- tests/tc054/expected.txt
Which are actually more then deprecated...just the following step: removed.
> array proposals, remove "sort" and "reverse"

- src/server/autocomplete/localuse.d
- tests/imports/b.d
- tests/tc003/file.d
- tests/tc003/run.sh
- tests/tc005/file.d
- tests/tc005/run.sh
- tests/tc028/file.d
- tests/tc029/file.d
- tests/tc029/run.sh
- tests/tc041/file.d
- tests/tc041/run.sh
- tests/tc042/file.d
- tests/tc042/run.sh
- tests/tc045/file.d
- tests/tc045/run.sh
- tests/tc047/file.d
- tests/tc047/run.sh
- tests/tc048/file.d
- tests/tc048/run.sh
- tests/tc049/expected3.txt
- tests/tc049/file.d
- tests/tc049/run.sh
- tests/tc050/file.d
- tests/tc050/run.sh
For a more consistent code style. I also found a segfault case in tc045 which needs to be investigated
> Use tabs everywhere

- src/common/messages.d
- src/server/main.d
A few indentation fixes (there were mixed tabs/spaces once + 2 spaces in a function argument list) and grouping together of msgpacking + error handling responses & sending them over a socket
> Simplify server main

- build.bat
Actually here it only succeeds after this change
> fix the bat - stdx file scanner already fully recursive

- src/dcd/common/messages.d
Seems to work just fine now, feel free to shrink back the buffer to 16kb and to fix the weird `char` problem.
> Big msgpack woes

- .travis.yml
- makefile
See also: https://github.com/dlang-community/D-Scanner/pull/573
> Deploy binaries to GitHub releases (Linux/MacOS)

- dub.json
- tests/tc_incomplete_switch/expected1.txt
- tests/tc_incomplete_switch/file.d
- tests/tc_incomplete_switch/run.sh
The bot cant be used here, because of the test case.
> fix #453 - failure in incomplete switch

- .travis.yml
- makefile
- release-windows.sh
- release.sh
Incorporates all recent improvements from DScanner (including building the Windows binary on Travis).
> Update release scripts

- dub.json
ping @andre2007, should be good this time
> fix #419 - server freezed under Win32 when caching the imports

- .travis.yml
- build.bat
- release-windows.sh
Similar to https://github.com/dlang-community/D-Scanner/pull/623.
I already uploaded the binaries for the last release.
> Build win64 binaries

- tests/run_tests.sh
> Fix #455 - Make the server startup more stable

- .gitignore
- build.bat
- dub.json
- makefile
- release-windows.sh
- src/dcd/client/client.d
- src/dcd/common/dcd_version.d
- src/dcd/server/main.d
> Improve automatic version generation - fix #497

- README.md
- dub.json
- src/dcd/client/client.d
- src/dcd/common/messages.d
- src/dcd/server/main.d
- tests/run_tests.sh
- tests/tc_rm_import/expected1.txt
- tests/tc_rm_import/file.d
- tests/tc_rm_import/run.sh
> fix #521 - Add a request allowing to remove a set of import path

- dub.json
This one will also fix many strange things people could encounter, since a couple of months, when importing code containing contracts.
> fix issue #489 - fix issue #523, mess in scopes

- dub.json
- tests/tc_anon_class/expected1.txt
- tests/tc_anon_class/expected2.txt
- tests/tc_anon_class/file1.d
- tests/tc_anon_class/file2.d
- tests/tc_anon_class/run.sh
And as bonus fix a possible crash, as found in D-Scanner.
> Add support for auto anon class completion, close #532

- dub.json
- dubhash.d
Same as for [dfmt](https://github.com/dlang-community/dfmt/pull/411)
> Prevent dub from blindly rebuilding every time

- dub.json
Same as https://github.com/dlang-community/dfmt/pull/414
> Fix dubhash.d for packages depending on dcd

- src/dcd/server/autocomplete/complete.d
- tests/tc_issue558/expected.txt
- tests/tc_issue558/file.d
- tests/tc_issue558/run.sh
Rewritten to be more readable but mostly less sloppy. Please test.
> fix #558 - regression in import completion due to FQN autocomplete

- tests/tc_import_symbol_list/.gitignore
- tests/tc_import_symbol_list/file.d
- tests/tc_import_symbol_list/newpackage/newmodule.d
- tests/tc_import_symbol_list/run.sh
This tests for the regression introduced by the merged version of dlang-community/dsymbol#114.
> Add lazy import regression test (dlang-community/dsymbol#114)

- src/dcd/server/autocomplete/util.d
- tests/tc_bang_op_or_template/expected1.txt
- tests/tc_bang_op_or_template/expected2.txt
- tests/tc_bang_op_or_template/file.d
- tests/tc_bang_op_or_template/run.sh
xref #366, where some similar code was removed, although my PR doesn't broke the test cases added then.
> fix #584 - crash when completing and if the previous expression is negated

- .travis.yml
- dub.json
- tests/tc010/expected1.txt
- tests/tc010/expected2.txt
- tests/tc_accesschain_type/expected.txt
- tests/tc_accesschain_type/file.d
- tests/tc_accesschain_type/run.sh
- tests/tc_anon_class/expected1.txt
- tests/tc_anon_struct/expected.txt
- tests/tc_anon_struct/file.d
- tests/tc_anon_struct/run.sh
- tests/tc_empty_module/file.d
- tests/tc_empty_module/run.sh
- dparse & dsymbol: pull the recent enhancements and fixes
- containers don't need to be fixed to a particular version anymore
> upgrade dependencies

- dub.json
- src/dcd/server/autocomplete/complete.d
- tests/tc_access_modifiers/bar.d
- tests/tc_access_modifiers/expected1.txt
- tests/tc_access_modifiers/expected1_1.txt
- tests/tc_access_modifiers/expected2.txt
- tests/tc_access_modifiers/expected3.txt
- tests/tc_access_modifiers/file1.d
- tests/tc_access_modifiers/file2.d
- tests/tc_access_modifiers/run.sh
this partially implements #317 (it's only implemented for completion right now, not for goto declaration)
depends on dlang-community/dsymbol#139
> make private symbols not show up in auto complete

- dub.json
- tests/tc_erroneous_body_content/expected1.txt
- tests/tc_erroneous_body_content/expected2.txt
- tests/tc_erroneous_body_content/file.d
- tests/tc_erroneous_body_content/run.sh
This requires https://github.com/dlang-community/libdparse/pull/359.
> fix #600 - Wrong scope for parameter solving in nested funcs

- .github/workflows/ci.yml
> Use gnu tar in osx build

- .gitmodules
stdx-allocator is no longer used within DCD
containers was moved to dlang-community, upgraded to current version there too.
> Remove stdx-allocator submodule and update containers to 0.9.0

- src/dcd/server/autocomplete/complete.d
- src/dcd/server/autocomplete/ufcs.d
- tests/tc_ufcs_calltip_in_func/expected.txt
- tests/tc_ufcs_calltip_in_func/file.d
- tests/tc_ufcs_calltip_in_func/run.sh
I have added paren completion for UFCS, Im not sure if I need to remove the first param for the calltip.
> Added paren completion for UFCS (calltip completion)

- dsymbol/src/dsymbol/builtin/names.d
Also auto-generate the istring value from an UDA, to make it easier to add/remove things without worrying about breakage.
@vushu wanna look at this?
> Document special breadcrumb/symbol names

- dsymbol/src/dsymbol/ufcs.d
- tests/tc_ufcs_array_type_completion/expected_array_test.txt
- tests/tc_ufcs_array_type_completion/file.d
- tests/tc_ufcs_array_type_completion/run.sh
> fix UFCS with partial completion, fix #731

- .github/workflows/pr_info_intro.yml
- .github/workflows/pr_info_post.yml
- .github/workflows/pr_info_untrusted.yml
- ci/request_time_stats.d
- ci/summary_comment.sh
- ci/summary_comment_diff.sh
- src/dcd/server/main.d
- tests/run_tests.sh
works basically the same like DUB comments
> add PR comments that show build statistics, speed & RAM usage

- common/src/dcd/common/constants2.d
- constants-gen/generator.d
- constants-gen/pragma.dd
- constants-gen/traits.dd
- tests/tc_traits/expected.txt
we haven't run this in too long, so manually verifying changes isn't really feasible right now. Will just merge once tests pass
> auto-update ddoc-based constants

- common/src/dcd/common/messages.d
This code logic is dumb, it should be greatly simplified, i'll try to do it in a different PR, let's just this deprecation warning first
> Fix deprecation warning

- dsymbol/src/dsymbol/conversion/first.d
- tests/tc_ctors/expected.txt
- tests/tc_ctors/file.d
- tests/tc_ctors/run.sh
> fix parameters in constructors being treated as fields

- dsymbol/src/dsymbol/conversion/package.d
- src/dcd/server/autocomplete/inlayhints.d
- tests/tc_inlay_hints/expected.txt
> support inlay hints inside functions
